apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  desktop-token: |-
    {{ randAlphaNum 18 | b64enc }}
  docker-user: |-
    {{ .Values.luna.user | b64enc }}
  docker-pass: |-
    {{ .Values.luna.pass | b64enc }}
  docker-registry: |-
    {{ .Values.luna.reg | b64enc }}