apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - port: 5900
    targetPort: 5900
    protocol: TCP
    name: vnc
  - port: 80
    targetPort: 80
    protocol: TCP
    name: novnc