apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 5901
      targetPort: 5901
      protocol: TCP
      name: vnc
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: novnc